import Head from "next/head";
import Header from "../components/Home/Header";
import BannerSection from "../components/Home/BannerSection";
import GameLogo from "../components/Home/GameLogo";
import AboutSection from "../components/Home/AboutSection";
import TournamentSection from "../components/Home/TournamentSection";

export default function Home() {
  return (
    <div className="container relative">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <BannerSection />
      <GameLogo />
      <AboutSection />
      <TournamentSection />
    </div>
  )
}
