import Head from "next/head";
import Header from "../components/Home/Header";
import BannerSection from "../components/Home/BannerSection";
import GameLogo from "../components/Home/GameLogo";
import AboutSection from "../components/Home/AboutSection";
import TournamentSection from "../components/Home/TournamentSection";
import Web3 from 'web3'

export default function Home() {
  // Empty web3 instance
  

const getWeb3 = async (isFirstLoad: boolean) => {
    try {
        let web3: Web3;
        if (window.ethereum) {
            web3 = new Web3(window.ethereum);
            // Ask User permission to connect to Metamask
            if (!isFirstLoad) {
                try {
                    await window.ethereum.enable();
                } catch (err) {
                    console.log('Transaction rejected by user:', err)
                };
            };
        } else if (window.web3) {
            web3 = new Web3(window.web3.currentProvider);
        } else {
            window.alert('Non-Ethereum browser detected. Please install MetaMask plugin');
            return;
        };

        dispatch(setWeb3(web3));  // Update web3 into Redux state

        // ...
    } catch (err) {
        console.log('Error in Web3.tsx -> getWeb3(): ', err);
    };
};






  return (
    <div className="container relative">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <BannerSection />
      <GameLogo />
      <AboutSection />
      <TournamentSection />
    </div>
  )
}
